//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_030101
{
    using System;
    using System.Collections.Generic;
    
    public partial class serviceclient
    {
        public int ID { get; set; }
        public int ServiceID { get; set; }
        public System.DateTime StartTime { get; set; }
        public int ClientID { get; set; }
        public string Comment { get; set; }
    
        public virtual serviceclient serviceclient1 { get; set; }
        public virtual serviceclient serviceclient2 { get; set; }
        public virtual serviceclient serviceclient11 { get; set; }
        public virtual serviceclient serviceclient3 { get; set; }
        public virtual serviceclient serviceclient12 { get; set; }
        public virtual serviceclient serviceclient4 { get; set; }
        public virtual serviceclient serviceclient13 { get; set; }
        public virtual serviceclient serviceclient5 { get; set; }
    }
}
